### ISSUE TITLE
Bei Bibliografia was vertauscht

### ISSUE THREAD

**Issue by pedrosepulveda** [cceh/pessoa#304]
Bei Índices / Bibliografia ist der Text, der bei Outras fontes da obra de Fernando Pessoa sein sollte bei 
Sobre a obra de Fernando Pessoa, und umgekehrt. Bitte richtig stellen. Bei dem letzten Eintrag von "Sobre a obra de Fernando Pessoa" ist noch das Zeichen > vor Uribe, bitte loeschen.

**Comment by pedrosepulveda** [comment]
Erscheint immer noch vertauscht,  Zeichen > auch noch vor Uribe.

**Comment by pedrosepulveda** [comment]
Mehrere Titel sind ausserdem bei "Sobre a obra de Fernando Pessoa" weg, im Grunde alle Titel der Buecher sind weg, die die nicht mit " " angemerkt sind (weil es um Buecher und nicht um Artikel geht)

**Comment by hennyu** [comment]
Die Vertauschung und > vor Uribe sollten behoben sein (es war noch nicht richtig auf den Server übertragen worden, gut, dass Dir das aufgefallen war). Bei den Titeln war durch die Überarbeitung der Bibliographie etwas in der Codierung schiefgegangen. Siehst Du noch irgendwo Fehler?

**Comment by pedrosepulveda** [comment]
Bei mir ist jetzt Sobre a obra de Fernando Pessoa an der richtigen Stelle, aber Outras fontes da obra de Fernando Pessoa ist jetzt weg (Sobre a obra de Fernando Pessoa ist doppelt). > bleibt und alle Titel der Buecher sind nicht da.

**Comment by pedrosepulveda** [comment]
Ok, scheint mir jetzt gut!
