### ISSUE TITLE
Problem mit Sprachversionen auf der Seite

### ISSUE THREAD

**Issue by pedrosepulveda** [cceh/pessoa#350]
Es scheint ein Problem zu sein von Sprache zu Sprache zu wechseln, ich kann gar nicht auf die deutsche Version greifen, die englische kommt zunaechst vor aber sobald ich ins Portugiesische wechsele kann ich nicht zurueck ins Englische. Bei índices, auf Portugiesisch, steht "bibliography", statt "Bibliografia".

**Comment by araborn** [comment]
Sollte jetzt wieder ordnungsgemäß funktionieren.
