### ISSUE TITLE
Angabe der Seite: p. statt pp.

### ISSUE THREAD

**Issue by pedrosepulveda** [cceh/pessoa#355]
Hallo Ulrike, mir ist aufgefallen dass bei vielen der publizierten Gedichte, oben, im Header, so was zu lesen ist "pp. X". Man verwendet aber nur "pp." wenn er sich um mehrere Seiten handelt, so bsw. "pp. 303-306". Kannst du das so aendern dass wenn eine einzelne Seite angegeben wird dann nur "p." vorkommt? Wenn es einfacher ist kann man auch "p." fuer alle Faelle nehmen, auch die mit mehreren Seiten, was nicht geht ist "pp." fuer eine einzelne Seite. Ich wollte dann auch ein paar Seitenzahlen ergaenzen, die noch nicht angegeben sind, aber das sollte erstmal korrigiert werden.

**Comment by hennyu** [comment]
verschoben in pessoa-issue
