### ISSUE TITLE
Missing Source File (`app/modules/charts.xqm`)

### ISSUE THREAD

**Issue by schlusslicht** [cceh/pessoa#802]
It appears that the file `charts.xqm`, which is referenced from [`app.xql`](https://github.com/cceh/pessoa/blob/master/app/modules/app.xql#L19) and [`view.xql`](https://github.com/cceh/pessoa/blob/master/app/modules/view.xql#L25) and should reside in `./app/modules` is missing from the SCM. Is this by design and the respective file should be deployed manually? Otherwise I'd offer to open a pull request containing the `charts.xqm` as it's currently deployed.

**Comment by hennyu** [comment]
Hi @schlusslicht , thanks for the observation. We deleted charts.xqm on purpose. So we should, of course, also delete the references to it.

**Comment by hennyu** [comment]
I deleted the references to that module.
